### ISSUE TITLE
Docker image: Requested  dns-multi plugin not installed

### ISSUE THREAD

**Issue by renne** [alexzorin/certbot-dns-multi#7]
I get the following error message:
```
Saving debug log to /var/log/letsencrypt/letsencrypt.log
The requested  dns-multi plugin does not appear to be installed
Ask for help or search for solutions at https://community.letsencrypt.org. See the logfile /var/log/letsencrypt/letsencrypt.log or re-run Certbot with -v for more details.
```
Why does the `-a dns-multi` option fail in the docker image?

**Comment by alexzorin** [comment]
Using the example command listed at https://github.com/alexzorin/certbot-dns-multi#via-docker and the latest published image, I don't get this error. If you want help, you'll need to show me exactly how to reproduce the error you're getting, from scratch.

**Comment by renne** [comment]
I'm trying to create a YAML config in a Portainer stack.
The image works on the command line of the docker host.
When I try to run the following YAML

```
  certbot:
    image: ghcr.io/alexzorin/certbot-dns-multi
    volumes:
      - certs:/etc/letsencrypt
    command: certonly --non-interactive --agree-tos -m letsencrypt@<mydomain>.de -a dns-multi --dns-multi-credentials /etc/letsencrypt/dns-multi.ini -d "<mydomain>.de" -d "*.<mydomain>.de" --dry-run
```
the error message is
```
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Simulating renewal of an existing certificate for <mydomain>.de and *.<mydomain>.de
unrecognized DNS provider: INWX
Ask for help or search for solutions at https://community.letsencrypt.org. See the logfile /var/log/letsencrypt/letsencrypt.log or re-run Certbot with -v for more details.
```
